### ISSUE TITLE
/validate task list

### ISSUE THREAD

**Issue by mjbp** [mjbp/components#9]
- [x] Unit test each fn
- [x] Integration test each validation method for both .net and html5
- [x] Refactor opaque and long fns
- [x] Add API for destroying and initialising
- [x] Add API for updating validator by group
